spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: BackEndService
server:
  port: 9000
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never